### ISSUE TITLE
[%key:common::config_flow::error::invalid_auth%]

### ISSUE THREAD

**Issue by THEthatdude** [bjhiltbrand/drone_mobile_home_assistant#30]
![Screenshot_20231107_122849_Home Assistant](https://github.com/bjhiltbrand/drone_mobile_home_assistant/assets/69739301/fa160016-b017-4051-bce3-18fca20be896)

Hello

I know this project isn't maintained but I at least wanted to put this here as a note- seems this integration has finally stopped working for me- I was getting lots of invalid auth errors- I tried to remove and re-add the integration but I get the error above- and this error in the logs:

403 Client Error: Forbidden for url: https://cognito-idp.us-east-1.amazonaws.com/

Not sure if dronemobile changed their api access or maybe it's just a standalone issue for my HA Instance

**Comment by bjhiltbrand** [comment]
I have worked through the authentication flow again via fiddler, postman, and home assistant, and all avenues are still authenticating for me. I did have an issue for a while trying to authenticate and it was returning a 403 like you have received, until I realized that I was typing in the wrong password. Once I fixed that, I had no issue. I have updated the python library and the home assistant integration with some more debug points, though. If you want to download the latest code and then put the integration into debug mode before trying to sign in, it might give a better indication of what is going on. Also, I know this has bitten me in the past, but are you making sure that they username field is an email address? I forget that every once in a while. ;)

**Comment by THEthatdude** [comment]
Hi- thank you for your guidance- I'm still getting the same error in the logs and an "Invalid Credentials" error in the config. I made sure to copy and paste my email and password straight from my dronemobile login but it still gives me the error. I changed my password but it still had the same error. I can login online but not through home assistant. How do I enable the advanced debugging?
Side note but possibly related- I received an email from dronemobile saying they were going to be adding 2FA in the future as I was trying to login via home assistant- not sure if it was a coincidence or if it's related.

**Comment by bjhiltbrand** [comment]
> Hi- thank you for your guidance- I'm still getting the same error in the logs and an "Invalid Credentials" error in the config. I made sure to copy and paste my email and password straight from my dronemobile login but it still gives me the error. I changed my password but it still had the same error. I can login online but not through home assistant. How do I enable the advanced debugging?

How familiar are you with Postman? If you are, would you mind running the post call to connect to Amazon Cognito?

[Compustar Test.postman_collection.json](https://github.com/bjhiltbrand/drone_mobile_home_assistant/files/13367647/Compustar.Test.postman_collection.json)

You should only need to enter your email and password here and click send.
![image](https://github.com/bjhiltbrand/drone_mobile_home_assistant/assets/11344821/34a99dab-1314-4a20-ac4b-538d0c75f99d)

If you can, please let me know what response you get back. This will help determine if the issue is coming from home assistant or from DroneMobile.

>Side note but possibly related- I received an email from dronemobile saying they were going to be adding 2FA in the future as I was trying to login via home assistant- not sure if it was a coincidence or if it's related.

I just looked at my email and saw that as well. It looks like it will be optional to start, but once it is available, I'll see about setting up a way in the authentication flow to accept a token. Thanks for the heads up.

**Comment by THEthatdude** [comment]
I just tried setting up postman- I think it all worked, It gave a status 200 OK, and the body result gave an Authentication result with an access token, ID token, refresh token and token type "bearer". (I'm not sure if it's a private token so I didn't want to post a screenshot)
Here's from the Headers page:
![headers postman test](https://github.com/bjhiltbrand/drone_mobile_home_assistant/assets/69739301/540d07b5-55e2-424f-86a5-c10c0076f602)

**Comment by bjhiltbrand** [comment]
Yep, that's correct. That's so weird that it's not working for you, as the python library making the calls for Home Assistant is using the exact same headers and body that this postman call uses.

**Comment by bjhiltbrand** [comment]
Oh, you know what, how are you loading a new version of the plugin? If you are deleting the "drone_mobile" folder in the custom_components folder and then copying the folder back over, that should take care of clearing the caches. If you are replacing the files in the drone_mobile folder with the new ones, you'll need to also delete the "__pycache__" folder and restart Home Assistant. That should clear out any references to old libraries. I would do that, as well as get rid of any files that start with "drone_mobile" in your config folder. That should get you to a pretty clean slate. If it still doesn't take the username and password, and the error code is still a 403, then I'm running out of ideas. :(

**Comment by bjhiltbrand** [comment]
Crazy thought... Are there any special characters in your username or password? I wonder if any of them get stripped out by home assistant unless they're escaped?

**Comment by bjhiltbrand** [comment]
You could also take a look at the "drone_mobile_token.txt" file in your config folder if you have it. Take a look at the "expiry_date" field and make sure that it is set to some time in the future:

![image](https://github.com/bjhiltbrand/drone_mobile_home_assistant/assets/11344821/91d62dd7-1475-4c33-be9d-69bd4d380db1)

**Comment by bjhiltbrand** [comment]
Before all that, though, have you tried to trigger the clear_temp_token service call?

![image](https://github.com/bjhiltbrand/drone_mobile_home_assistant/assets/11344821/7e2d51dc-c8cf-47b0-aa46-34ae43c68290)

**Comment by THEthatdude** [comment]
> Oh, you know what, how are you loading a new version of the plugin?

I tried a totally fresh state- deleted all traces of drone_mobile, restarted, the copied the new drone_mobile folder to custom components, then restarted again.

>Crazy thought... Are there any special characters in your username or password?

I was going to try this suggestion but their password security requires a special character I couldn't remove it

>Before all that, though, have you tried to trigger the clear_temp_token service call?

I can't run this service since I haven't setup the integration successfully? None of the drone mobile services show up- im guessing because it's not configured. I did make sure there were no traces of a token

>You could also take a look at the "drone_mobile_token.txt"

Don't have a token :(

After re-installing the integration I still get the 403 error in the system logs

I'm at a loss too this is super strange

**Comment by THEthatdude** [comment]
Possible dumb idea- Can I take the token from postman somehow an just copy it to home assistant? I'm not sure how the whole API works or if it would mess up the config flow

**Comment by crizz6396** [comment]
I'm having the same issue

**Comment by bjhiltbrand** [comment]
> Possible dumb idea- Can I take the token from postman somehow an just copy it to home assistant? I'm not sure how the whole API works or if it would mess up the config flow

I was thinking about that, too, but I don't think it would work, as HA has to make it through config flow to actually setup the integration, and the whole idea of that is to go through the authentication step to get the token. Let me think on that for a bit and see if there's a way that I could have config flow check for an existing non-expired token before asking for a username and password.

Of course, I'd like to try to figure out why it's not working for some people ONLY through HA. I setup a fresh instance of HA, with no other integrations except this one, and was able to authenticate just fine. There has to be something going on, I just don't know what yet. :(

**Comment by bjhiltbrand** [comment]
Alright, turns out that the stuff I did to create more logging in the python package ended up breaking the requests. I have fixed that and have pushed a new version of the integration. Please download the latest code and try again.

**Comment by bjhiltbrand** [comment]
If you want to take a look at the python package and how communication is taking place with DroneMobile, have a look here:

https://github.com/bjhiltbrand/drone_mobile_python

If you download that package, and run the bin/demo.py file from a command line, passing in your username (email) and password, it should return the json data for the vehicles on your account. If you run that, and get a valid response back, it will show us that the communication with the API is working and the issue lies within Home Assistant.

**Comment by THEthatdude** [comment]
![demo dronemobile failed](https://github.com/bjhiltbrand/drone_mobile_home_assistant/assets/69739301/ed0712a8-2c00-4b5f-b6c3-41997fa18f11)
Didn't work for me on same local network- Come to think of it I did the postman test from my work computer I wonder if my homes IP is blocked or something on the dronemobile side?

**Comment by THEthatdude** [comment]
YUP I just tested on my work computer and it works just fine- from inside my own network I'm getting the 403 error. So at least that narrows it down

**Comment by bjhiltbrand** [comment]
Yeah, I was seeing a 403 for an authentication failure. A 400 would be a generic "bad request", almost like it's malformed. Well, at least it's good to know the library and plugin are working like they should now. I wonder what is different on your local network, and if the issue is that your IP has been blacklisted, or if your networking equipment is messing up the request? Is your IP static on your home network? Could you try forcing an IP change, or trying from a VPN?

**Comment by THEthatdude** [comment]
I have a static IP for home, I might experiment with a VPN but that would suck if i got IP Banned- do you think I need to call drone mobile support?

**Comment by THEthatdude** [comment]
I went ahead and e-mailed dronemobile support- I think you can close this issue since your integration is working fine - thank you for your help I really appreciate it!

**Comment by bjhiltbrand** [comment]
I would try to access your drone mobile account from your phone, connected to wifi, with a fresh sign on to see if the official app is blocking you. You could also try logging in on dronemobile's website (https://accounts.dronemobile.com/login).

As a follow up, I just tried using incorrect passwords and email addresses in postman and in HA, and they both returned 400 errors for me this time. I wonder if something changed on cognito's end? Regardless, there is a helpful message returned in the body as to what type of exception was thrown:

![image](https://github.com/bjhiltbrand/drone_mobile_home_assistant/assets/11344821/fdfc4274-28c9-41b1-bc6c-f6628dca09b3)


I might take a bit of time and update the logic to check the body of the return payload to better form failure messages.

**Comment by THEthatdude** [comment]
>I would try to access your drone mobile account from your phone, connected to wifi, with a fresh sign on to see if the official app is blocking you. You could also try logging in on dronemobile's website (https://accounts.dronemobile.com/login).

Welp I can't log into the website from my PC- It says username or password is incorrect. That is strange. I'll test my phones official app when I get home

**Comment by bjhiltbrand** [comment]
> Welp I can't log into the website from my PC- It says username or password is incorrect. That is strange. I'll test my phones official app when I get home

I would approach the ticket with DroneMobile support from that angle - That you can't login on THEIR website, not that you're tying to access their undocumented API. ;) I know I was required to change my password a few months ago, I wonder if it has anything to do with that? Support might have you do that anyway.

**Comment by THEthatdude** [comment]
Yup I'm in the cue with support lol- I'll update ya when I figure out what's going on. I had to change my password a while back too but I didn't have this issue until recently.

**Comment by crizz6396** [comment]
I can confirm with 100% certainty that they are blacklist ip addresses.  I cannot log into the website or the app when I am connected to my home network.  As soon as I disconnect from wifi, everything works.

I sent an email to drone support asked my my ip address to be white listed.  Let's see what happens.

**Comment by crizz6396** [comment]
Can we take our cookie session and manually add it to HA.  Once you are authenticated, the site works.

**Comment by THEthatdude** [comment]
Wow I am very impressed with support- they made some changes to their login servers and everything is working again for me! @crizz6396 you might want to try logging in again to see if it's fixed for you as well

**Comment by crizz6396** [comment]
That's great.  I forced an ip change.  Hopefully it will keep working.  What did you tell them to make them make the changes

**Comment by THEthatdude** [comment]
I just told them all the login issues (and api issues) I was experiencing and support passed it to the dev team and they fixed it- support was super nice it was one of my best tech support experiences probably ever. I just dumped all the information I knew from testing and they fixed it

**Comment by crizz6396** [comment]
That's awesome.  For a second there I thought this was going to be another myq BS intentionally blocking users.

**Comment by bjhiltbrand** [comment]
> That's awesome.  For a second there I thought this was going to be another myq BS intentionally blocking users.

I try to keep this on the down-low and to not get too crazy with calls, so as not to draw their ire, but I often wonder if they'll block it at some point, too.

**Comment by crizz6396** [comment]
I have 2 cars connected.  I reset it to every 15 minutes.  Hopefully that is long enough.

**Comment by bjhiltbrand** [comment]
> I have 2 cars connected. I reset it to every 15 minutes. Hopefully that is long enough.

I do, too. The default 5 minute interval seems to work fine for me (Once authenticated).
